create table if not exists public.tabandatato_scores (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    player text not null default 'Guest',
    score integer not null default 0,
    difficulty text,
    rule_mode text,
    daily boolean not null default false,
    skin text,
    catches integer not null default 0,
    max_streak integer not null default 0,
    powerups integer not null default 0
);

alter table public.tabandatato_scores
add column if not exists session_id text;

create table if not exists public.tabandatato_dual_scores (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    winner text not null default 'Unknown',
    loser text not null default 'Unknown',
    winner_score integer not null default 0,
    loser_score integer not null default 0,
    variant text
);

alter table public.tabandatato_dual_scores
add column if not exists session_id text;

create table if not exists public.tabandatato_profiles (
    player_key text primary key,
    player text not null default 'Guest',
    xp integer not null default 0,
    games integer not null default 0,
    total_catches integer not null default 0,
    best_score integer not null default 0,
    best_streak integer not null default 0,
    powerups integer not null default 0,
    wins integer not null default 0,
    losses integer not null default 0,
    favorite_skin text,
    updated_at timestamptz not null default now()
);

alter table public.tabandatato_scores enable row level security;
alter table public.tabandatato_dual_scores enable row level security;
alter table public.tabandatato_profiles enable row level security;

drop policy if exists "Scores are readable by anyone" on public.tabandatato_scores;
drop policy if exists "Scores can be submitted by anyone" on public.tabandatato_scores;
drop policy if exists "Dual scores are readable by anyone" on public.tabandatato_dual_scores;
drop policy if exists "Dual scores can be submitted by anyone" on public.tabandatato_dual_scores;
drop policy if exists "Profiles are readable by anyone" on public.tabandatato_profiles;
drop policy if exists "Profiles can be upserted by anyone" on public.tabandatato_profiles;
drop policy if exists "Profiles can be updated by anyone" on public.tabandatato_profiles;

create policy "Scores are readable by anyone"
on public.tabandatato_scores
for select
to anon
using (true);

create policy "Scores can be submitted by anyone"
on public.tabandatato_scores
for insert
to anon
with check (
    score >= 0
    and score <= 100000
    and catches >= 0
    and catches <= 100000
    and max_streak >= 0
    and max_streak <= 100000
    and powerups >= 0
    and powerups <= 100000
    and length(player) between 1 and 40
);

create policy "Dual scores are readable by anyone"
on public.tabandatato_dual_scores
for select
to anon
using (true);

create policy "Dual scores can be submitted by anyone"
on public.tabandatato_dual_scores
for insert
to anon
with check (
    winner_score >= 0
    and winner_score <= 100000
    and loser_score >= 0
    and loser_score <= 100000
    and length(winner) between 1 and 40
    and length(loser) between 1 and 40
);

create policy "Profiles are readable by anyone"
on public.tabandatato_profiles
for select
to anon
using (true);

create policy "Profiles can be upserted by anyone"
on public.tabandatato_profiles
for insert
to anon
with check (
    xp >= 0
    and xp <= 9999999
    and games >= 0
    and total_catches >= 0
    and best_score >= 0
    and best_score <= 100000
    and best_streak >= 0
    and best_streak <= 100000
    and length(player) between 1 and 40
    and length(player_key) between 1 and 40
);

create policy "Profiles can be updated by anyone"
on public.tabandatato_profiles
for update
to anon
using (true)
with check (
    xp >= 0
    and xp <= 9999999
    and games >= 0
    and total_catches >= 0
    and best_score >= 0
    and best_score <= 100000
    and best_streak >= 0
    and best_streak <= 100000
    and length(player) between 1 and 40
    and length(player_key) between 1 and 40
);

create index if not exists tabandatato_scores_score_idx
on public.tabandatato_scores (score desc, created_at desc);

create index if not exists tabandatato_dual_scores_score_idx
on public.tabandatato_dual_scores (winner_score desc, loser_score desc, created_at desc);

create index if not exists tabandatato_profiles_xp_idx
on public.tabandatato_profiles (xp desc, updated_at desc);
